version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-mrbs_db}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "3010:5432"

  backend:
    build: ./backend
    environment:
      DB_URL: postgresql://${DB_USERNAME:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_DATABASE:-mrbs_db}
      SEED_USER_NAME: ${SEED_USER_NAME:-admin}
      SEED_USER_ROLE: ${SEED_USER_ROLE:-admin}
      CORS: ${CORS:-["http://localhost:3030"]}
    depends_on:
      - db
    ports:
      - "3020:3000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3020}
    depends_on:
      - backend
    ports:
      - "3030:80"

volumes:
  db_data:
